name: MCSnake
version: ${project.version}
main: com.duckelekuuk.mcsnake.MCSnake
authors: [Duckelekuuk]
description: Allows you to play snake in minecraft
website: https://duckelekuuk.com
depends: WorldEdit